//
//  CollectionDetailView.swift
//  Constellation
//
//  Created by Vivek  Sen on 2/27/26.
//

import SwiftUI
import SwiftData

struct CollectionDetailView: View {
    @Environment(\.modelContext) private var modelContext
    @Bindable var collection: ItemCollection
    
    @Query private var movies: [Movie]
    @Query private var tvShows: [TVShow]
    
    @State private var showingAddItems = false
    @State private var showingEditMetadata = false
    @State private var generatingInsight = false
    
    var collectionMovies: [Movie] {
        let ids = Set(collection.movieIDs)
        return movies.filter { ids.contains($0.id.uuidString) }
    }
    
    var collectionTVShows: [TVShow] {
        let ids = Set(collection.showIDs)
        return tvShows.filter { ids.contains($0.id.uuidString) }
    }
    
    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 10) {
                    Text(collection.name)
                        .font(.title2)
                        .fontWeight(.bold)
                    
                    if let desc = collection.desc, !desc.isEmpty {
                        if desc.hasPrefix("auto-theme::") {
                            Text("Auto-generated from your shared theme graph")
                                .font(.body)
                                .foregroundStyle(.secondary)
                        } else {
                            Text(desc)
                                .font(.body)
                                .foregroundStyle(.secondary)
                        }
                    }
                    
                    HStack(spacing: 12) {
                        Label("\(collection.totalItemCount) total", systemImage: "square.stack.3d.up")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                        
                        if collection.isAutoGenerated {
                            Label("AI-generated", systemImage: "sparkles")
                                .font(.caption)
                                .foregroundStyle(.purple)
                        }
                    }
                }
                .padding(.vertical, 4)
            }
            
            Section("Collection Insight") {
                if let insight = collection.aiInsight, !insight.isEmpty {
                    Text(insight)
                        .font(.body)
                } else {
                    Text("No insight yet. Generate one to summarize how these items connect.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                
                Button {
                    Task {
                        await generateInsight()
                    }
                } label: {
                    if generatingInsight {
                        HStack {
                            ProgressView()
                            Text("Generating...")
                        }
                    } else {
                        Label("Generate Insight", systemImage: "brain")
                    }
                }
                .disabled(generatingInsight || (collectionMovies.isEmpty && collectionTVShows.isEmpty))
            }
            
            if !collectionMovies.isEmpty {
                Section("Movies") {
                    ForEach(collectionMovies) { movie in
                        NavigationLink(destination: MovieDetailView(movie: movie)) {
                            HStack(spacing: 12) {
                                PosterThumb(urlString: movie.posterURL, fallback: "🎬")
                                
                                VStack(alignment: .leading, spacing: 4) {
                                    Text(movie.title)
                                        .font(.headline)
                                    
                                    if let year = movie.year {
                                        Text(String(year))
                                            .font(.caption)
                                            .foregroundStyle(.secondary)
                                    }
                                }
                            }
                        }
                        .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                            Button(role: .destructive) {
                                removeMovie(movie)
                            } label: {
                                Label("Remove", systemImage: "trash")
                            }
                        }
                    }
                }
            }
            
            if !collectionTVShows.isEmpty {
                Section("TV Shows") {
                    ForEach(collectionTVShows) { show in
                        NavigationLink(destination: TVShowDetailView(show: show)) {
                            HStack(spacing: 12) {
                                PosterThumb(urlString: show.posterURL, fallback: "📺")
                                
                                VStack(alignment: .leading, spacing: 4) {
                                    Text(show.title)
                                        .font(.headline)
                                    
                                    if let year = show.year {
                                        Text(String(year))
                                            .font(.caption)
                                            .foregroundStyle(.secondary)
                                    }
                                }
                            }
                        }
                        .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                            Button(role: .destructive) {
                                removeTVShow(show)
                            } label: {
                                Label("Remove", systemImage: "trash")
                            }
                        }
                    }
                }
            }
            
            if collectionMovies.isEmpty && collectionTVShows.isEmpty {
                Section {
                    ContentUnavailableView(
                        "No Items Yet",
                        systemImage: "tray",
                        description: Text("Add movies or TV shows to this collection.")
                    )
                }
            }
        }
        .navigationTitle("Collection")
        .toolbar {
            ToolbarItemGroup(placement: .topBarTrailing) {
                Button("Edit") {
                    showingEditMetadata = true
                }
                
                Button {
                    showingAddItems = true
                } label: {
                    Label("Add Items", systemImage: "plus")
                }
            }
        }
        .sheet(isPresented: $showingAddItems) {
            AddItemsToCollectionView(collection: collection)
        }
        .sheet(isPresented: $showingEditMetadata) {
            EditCollectionMetadataView(collection: collection)
        }
    }
    
    private func removeMovie(_ movie: Movie) {
        collection.removeItem(id: movie.id, type: .movie)
        collection.aiInsight = nil
        try? modelContext.save()
    }
    
    private func removeTVShow(_ show: TVShow) {
        collection.removeItem(id: show.id, type: .tvShow)
        collection.aiInsight = nil
        try? modelContext.save()
    }
    
    private func generateInsight() async {
        generatingInsight = true
        let insight = await SynthesisEngine.shared.generateCollectionInsight(
            collectionName: collection.name,
            movies: collectionMovies,
            tvShows: collectionTVShows
        )
        collection.aiInsight = insight
        try? modelContext.save()
        generatingInsight = false
    }
}

private struct PosterThumb: View {
    let urlString: String?
    let fallback: String
    
    var body: some View {
        if let urlString, let url = URL(string: urlString) {
            AsyncImage(url: url) { image in
                image
                    .resizable()
                    .aspectRatio(contentMode: .fill)
            } placeholder: {
                Rectangle().fill(Color.gray.opacity(0.25))
            }
            .frame(width: 44, height: 66)
            .clipShape(RoundedRectangle(cornerRadius: 8))
        } else {
            RoundedRectangle(cornerRadius: 8)
                .fill(Color.gray.opacity(0.2))
                .frame(width: 44, height: 66)
                .overlay {
                    Text(fallback)
                }
        }
    }
}

struct AddItemsToCollectionView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    
    @Bindable var collection: ItemCollection
    @Query(sort: \Movie.title) private var movies: [Movie]
    @Query(sort: \TVShow.title) private var tvShows: [TVShow]
    
    @State private var searchText = ""
    
    var filteredMovies: [Movie] {
        guard !searchText.isEmpty else { return movies }
        return movies.filter { $0.title.localizedCaseInsensitiveContains(searchText) }
    }
    
    var filteredTVShows: [TVShow] {
        guard !searchText.isEmpty else { return tvShows }
        return tvShows.filter { $0.title.localizedCaseInsensitiveContains(searchText) }
    }
    
    var body: some View {
        NavigationStack {
            List {
                if !filteredMovies.isEmpty {
                    Section("Movies") {
                        ForEach(filteredMovies) { movie in
                            selectableRow(
                                title: movie.title,
                                subtitle: movie.year.map(String.init),
                                selected: collection.contains(id: movie.id, type: .movie),
                                fallbackIcon: "🎬"
                            ) {
                                toggleMovie(movie)
                            }
                        }
                    }
                }
                
                if !filteredTVShows.isEmpty {
                    Section("TV Shows") {
                        ForEach(filteredTVShows) { show in
                            selectableRow(
                                title: show.title,
                                subtitle: show.year.map(String.init),
                                selected: collection.contains(id: show.id, type: .tvShow),
                                fallbackIcon: "📺"
                            ) {
                                toggleTVShow(show)
                            }
                        }
                    }
                }
            }
            .searchable(text: $searchText, prompt: "Search media")
            .navigationTitle("Add Items")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") {
                        collection.aiInsight = nil
                        try? modelContext.save()
                        dismiss()
                    }
                }
            }
        }
    }
    
    @ViewBuilder
    private func selectableRow(
        title: String,
        subtitle: String?,
        selected: Bool,
        fallbackIcon: String,
        action: @escaping () -> Void
    ) -> some View {
        Button(action: action) {
            HStack(spacing: 12) {
                RoundedRectangle(cornerRadius: 8)
                    .fill(selected ? Color.green.opacity(0.2) : Color.gray.opacity(0.15))
                    .frame(width: 34, height: 34)
                    .overlay {
                        Text(fallbackIcon)
                            .font(.caption)
                    }
                
                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .foregroundStyle(.primary)
                    
                    if let subtitle {
                        Text(subtitle)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                
                Spacer()
                
                Image(systemName: selected ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(selected ? Color.green : Color.secondary)
            }
        }
        .buttonStyle(.plain)
    }
    
    private func toggleMovie(_ movie: Movie) {
        if collection.contains(id: movie.id, type: .movie) {
            collection.removeItem(id: movie.id, type: .movie)
        } else {
            collection.addItem(id: movie.id, type: .movie)
        }
    }
    
    private func toggleTVShow(_ show: TVShow) {
        if collection.contains(id: show.id, type: .tvShow) {
            collection.removeItem(id: show.id, type: .tvShow)
        } else {
            collection.addItem(id: show.id, type: .tvShow)
        }
    }
}

struct EditCollectionMetadataView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    
    @Bindable var collection: ItemCollection
    
    @State private var name: String = ""
    @State private var descriptionText: String = ""
    @State private var isAutoGenerated = false
    
    var body: some View {
        NavigationStack {
            Form {
                Section("Collection Info") {
                    TextField("Name", text: $name)
                    TextField("Description (optional)", text: $descriptionText, axis: .vertical)
                        .lineLimit(2...5)
                }
                
                Section("Type") {
                    Toggle("AI-generated collection", isOn: $isAutoGenerated)
                }
            }
            .navigationTitle("Edit Collection")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        saveChanges()
                    }
                    .disabled(name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
            .onAppear {
                name = collection.name
                descriptionText = collection.desc ?? ""
                isAutoGenerated = collection.isAutoGenerated
            }
        }
    }
    
    private func saveChanges() {
        collection.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        
        let trimmedDesc = descriptionText.trimmingCharacters(in: .whitespacesAndNewlines)
        collection.desc = trimmedDesc.isEmpty ? nil : trimmedDesc
        collection.isAutoGenerated = isAutoGenerated
        
        try? modelContext.save()
        dismiss()
    }
}
