//
//  CollectionsView.swift
//  Constellation
//
//  Created by Vivek  Sen on 2/27/26.
//

import SwiftUI
import SwiftData

struct CollectionsView: View {
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \ItemCollection.createdDate, order: .reverse) private var collections: [ItemCollection]
    @Query private var movies: [Movie]
    @Query private var tvShows: [TVShow]
    
    @State private var showingCreateCollection = false
    @State private var autoGenerationSummary = ""
    @State private var showingAutoGenerationSummary = false
    
    var body: some View {
        NavigationStack {
            Group {
                if collections.isEmpty {
                    ContentUnavailableView {
                        Label("No Collections Yet", systemImage: "square.stack.3d.up")
                    } description: {
                        Text("Create a collection to organize movies and TV shows by theme, mood, or topic.")
                    } actions: {
                        Button("Create First Collection") {
                            showingCreateCollection = true
                        }
                        .buttonStyle(.borderedProminent)
                    }
                } else {
                    List {
                        ForEach(collections) { collection in
                            NavigationLink(destination: CollectionDetailView(collection: collection)) {
                                CollectionRow(collection: collection)
                            }
                        }
                        .onDelete(perform: deleteCollections)
                    }
                    .listStyle(.insetGrouped)
                }
            }
            .navigationTitle("Collections")
            .toolbar {
                ToolbarItemGroup(placement: .topBarTrailing) {
                    Button {
                        generateAutoCollections()
                    } label: {
                        Label("Generate Auto Collections", systemImage: "sparkles")
                    }
                    
                    Button {
                        showingCreateCollection = true
                    } label: {
                        Label("New Collection", systemImage: "plus")
                    }
                }
            }
            .sheet(isPresented: $showingCreateCollection) {
                CreateCollectionView()
            }
            .alert("Auto Collections Updated", isPresented: $showingAutoGenerationSummary) {
                Button("OK", role: .cancel) {}
            } message: {
                Text(autoGenerationSummary)
            }
        }
    }
    
    private func generateAutoCollections() {
        let result = CollectionGenerator.shared.generateThemeCollections(
            movies: movies,
            tvShows: tvShows,
            existingCollections: collections,
            modelContext: modelContext
        )
        
        autoGenerationSummary = "Created \(result.created), updated \(result.updated), based on \(result.consideredThemes) high-signal theme(s)."
        showingAutoGenerationSummary = true
    }
    
    private func deleteCollections(at offsets: IndexSet) {
        for index in offsets {
            modelContext.delete(collections[index])
        }
        
        try? modelContext.save()
    }
}

struct CollectionRow: View {
    let collection: ItemCollection
    
    var body: some View {
        HStack(spacing: 12) {
            ZStack {
                RoundedRectangle(cornerRadius: 12)
                    .fill(collection.isAutoGenerated ? Color.purple.opacity(0.15) : Color.blue.opacity(0.15))
                    .frame(width: 48, height: 48)
                
                Image(systemName: collection.isAutoGenerated ? "sparkles.rectangle.stack.fill" : "square.stack.3d.up.fill")
                    .foregroundStyle(collection.isAutoGenerated ? .purple : .blue)
            }
            
            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 6) {
                    Text(collection.name)
                        .font(.headline)
                        .lineLimit(1)
                    
                    if collection.isAutoGenerated {
                        Text("AI")
                            .font(.caption2)
                            .fontWeight(.semibold)
                            .padding(.horizontal, 6)
                            .padding(.vertical, 2)
                            .background(Color.purple.opacity(0.2))
                            .foregroundStyle(.purple)
                            .clipShape(Capsule())
                    }
                }
                
                if let desc = collection.desc, !desc.isEmpty {
                    if desc.hasPrefix("auto-theme::") {
                        Text("Auto-generated from shared themes")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    } else {
                        Text(desc)
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    }
                }
                
                Text("\(collection.totalItemCount) item\(collection.totalItemCount == 1 ? "" : "s")")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
        .padding(.vertical, 4)
    }
}

struct CreateCollectionView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    
    @State private var name = ""
    @State private var descriptionText = ""
    @State private var isAutoGenerated = false
    
    var body: some View {
        NavigationStack {
            Form {
                Section("Collection Info") {
                    TextField("Name", text: $name)
                    TextField("Description (optional)", text: $descriptionText, axis: .vertical)
                        .lineLimit(2...5)
                }
                
                Section("Type") {
                    Toggle("AI-generated collection", isOn: $isAutoGenerated)
                }
            }
            .navigationTitle("New Collection")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                
                ToolbarItem(placement: .confirmationAction) {
                    Button("Create") {
                        createCollection()
                    }
                    .disabled(name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
        }
    }
    
    private func createCollection() {
        let trimmedName = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedDescription = descriptionText.trimmingCharacters(in: .whitespacesAndNewlines)
        
        let collection = ItemCollection(
            name: trimmedName,
            description: trimmedDescription.isEmpty ? nil : trimmedDescription,
            isAutoGenerated: isAutoGenerated
        )
        
        modelContext.insert(collection)
        try? modelContext.save()
        dismiss()
    }
}
