//
//  ItemCollection.swift
//  Constellation
//
//  Created by Vivek  Sen on 2/27/26.
//

import Foundation
import SwiftData

@Model
final class ItemCollection {
    var id: UUID
    var name: String
    var desc: String?
    var coverImage: String?
    var createdDate: Date
    var isAutoGenerated: Bool
    var aiInsight: String?
    
    // UUIDs stored as String for lightweight cross-type references
    var movieIDs: [String]
    var showIDs: [String]
    var articleIDs: [String]
    var podcastIDs: [String]
    var bookIDs: [String]
    
    init(
        name: String,
        description: String? = nil,
        isAutoGenerated: Bool = false
    ) {
        self.id = UUID()
        self.name = name
        self.desc = description
        self.createdDate = Date()
        self.isAutoGenerated = isAutoGenerated
        self.movieIDs = []
        self.showIDs = []
        self.articleIDs = []
        self.podcastIDs = []
        self.bookIDs = []
    }
    
    var totalItemCount: Int {
        movieIDs.count + showIDs.count + articleIDs.count + podcastIDs.count + bookIDs.count
    }
    
    func contains(id: UUID, type: MediaType) -> Bool {
        let idString = id.uuidString
        switch type {
        case .movie: return movieIDs.contains(idString)
        case .tvShow: return showIDs.contains(idString)
        case .article: return articleIDs.contains(idString)
        case .podcast: return podcastIDs.contains(idString)
        case .book: return bookIDs.contains(idString)
        }
    }
    
    func addItem(id: UUID, type: MediaType) {
        let idString = id.uuidString
        
        switch type {
        case .movie:
            guard !movieIDs.contains(idString) else { return }
            movieIDs.append(idString)
        case .tvShow:
            guard !showIDs.contains(idString) else { return }
            showIDs.append(idString)
        case .article:
            guard !articleIDs.contains(idString) else { return }
            articleIDs.append(idString)
        case .podcast:
            guard !podcastIDs.contains(idString) else { return }
            podcastIDs.append(idString)
        case .book:
            guard !bookIDs.contains(idString) else { return }
            bookIDs.append(idString)
        }
    }
    
    func removeItem(id: UUID, type: MediaType) {
        let idString = id.uuidString
        
        switch type {
        case .movie:
            movieIDs.removeAll { $0 == idString }
        case .tvShow:
            showIDs.removeAll { $0 == idString }
        case .article:
            articleIDs.removeAll { $0 == idString }
        case .podcast:
            podcastIDs.removeAll { $0 == idString }
        case .book:
            bookIDs.removeAll { $0 == idString }
        }
    }
}
