//
//  CollectionGenerator.swift
//  Constellation
//
//  Created by Codex on 2/27/26.
//

import Foundation
import SwiftData

struct AutoCollectionGenerationResult {
    let created: Int
    let updated: Int
    let consideredThemes: Int
}

final class CollectionGenerator {
    static let shared = CollectionGenerator()
    
    private init() {}
    
    func generateThemeCollections(
        movies: [Movie],
        tvShows: [TVShow],
        books: [Book],
        podcasts: [PodcastEpisode],
        existingCollections: [ItemCollection],
        modelContext: ModelContext,
        maxCollections: Int = 6,
        minItemsPerTheme: Int = 2
    ) -> AutoCollectionGenerationResult {
        var themeMovies: [String: Set<String>] = [:]
        var themeShows: [String: Set<String>] = [:]
        var themeBooks: [String: Set<String>] = [:]
        var themePodcasts: [String: Set<String>] = [:]
        
        for movie in movies {
            for theme in movie.themes {
                themeMovies[theme, default: []].insert(movie.id.uuidString)
            }
        }
        
        for show in tvShows {
            for theme in show.themes {
                themeShows[theme, default: []].insert(show.id.uuidString)
            }
        }

        for book in books {
            for theme in book.themes {
                themeBooks[theme, default: []].insert(book.id.uuidString)
            }
        }

        for episode in podcasts {
            for theme in episode.themes {
                themePodcasts[theme, default: []].insert(episode.id.uuidString)
            }
        }
        
        let allThemes = Set(themeMovies.keys).union(themeShows.keys).union(themeBooks.keys).union(themePodcasts.keys)
        let rankedThemes = allThemes
            .map { theme -> (String, Int) in
                let movieCount = themeMovies[theme]?.count ?? 0
                let showCount = themeShows[theme]?.count ?? 0
                let bookCount = themeBooks[theme]?.count ?? 0
                let podcastCount = themePodcasts[theme]?.count ?? 0
                return (theme, movieCount + showCount + bookCount + podcastCount)
            }
            .filter { $0.1 >= minItemsPerTheme }
            .sorted { lhs, rhs in
                if lhs.1 == rhs.1 {
                    return lhs.0 < rhs.0
                }
                return lhs.1 > rhs.1
            }
            .prefix(maxCollections)
        
        var created = 0
        var updated = 0
        
        for (theme, _) in rankedThemes {
            let marker = "auto-theme::\(theme)"
            let displayName = "Theme: \(theme.replacingOccurrences(of: "-", with: " ").capitalized)"
            
            let movieIDs = Array(themeMovies[theme] ?? []).sorted()
            let showIDs = Array(themeShows[theme] ?? []).sorted()
            let bookIDs = Array(themeBooks[theme] ?? []).sorted()
            let podcastIDs = Array(themePodcasts[theme] ?? []).sorted()
            
            if let existing = existingCollections.first(where: { $0.isAutoGenerated && $0.desc == marker }) {
                existing.name = displayName
                existing.movieIDs = movieIDs
                existing.showIDs = showIDs
                existing.bookIDs = bookIDs
                existing.podcastIDs = podcastIDs
                existing.aiInsight = nil
                updated += 1
            } else {
                let collection = ItemCollection(name: displayName, description: marker, isAutoGenerated: true)
                collection.movieIDs = movieIDs
                collection.showIDs = showIDs
                collection.bookIDs = bookIDs
                collection.podcastIDs = podcastIDs
                modelContext.insert(collection)
                created += 1
            }
        }
        
        try? modelContext.save()
        
        return AutoCollectionGenerationResult(
            created: created,
            updated: updated,
            consideredThemes: rankedThemes.count
        )
    }
}
